Repository dbinclui-org/dbinclui-backend, pull requests merged in 2021-12, with the labels that each got.

#1 Adicionando README padrão do projeto
  README.md
Labels: documentation

#3 Feature/dbi 60 - Prettier e ESLINT
  .eslintrc.json
  README.md
  package-lock.json
  package.json
  src/index.ts
  tsconfig.json
Labels: documentation, feature

#4 Feature/DBI-55-2 - Criação documento/schema "guides"
  src/app/entities/guides.ts
  src/app/models/modelGuides.ts
Labels: feature

#5 Feature/dbi 54 - Conexão ao MongoDB
  .env.dev
  .eslintrc.json
  .gitignore
  package.json
  src/app.ts
  src/index.ts
Labels: feature

#6 Feature/dbi 60 - Prettier e ESLINT
  .eslintrc.json
  .prettierrc
  src/app.ts
  src/app/entities/guides.ts
  src/app/models/modelGuides.ts
  src/index.ts
Labels: feature

#8 Feature/DBI-57 - Estrutura de rotas
  package-lock.json
  src/app.ts
  src/app/routes/routes.ts
  src/index.ts
  yarn.lock
Labels: feature

#7 Feature/DBI-54 - Abstração conexão MongoDB e melhor .env
  .env.dev
  .env.sample
  .eslintrc.json
  .github/workflows/build.yaml
  .gitignore
  .prettierrc
  jest.config.ts
  package-lock.json
  package.json
  src/app.ts
  src/app/models/modelGuides.ts
  src/database/.gitkeep
  src/database/config.ts
  src/env.ts
  src/index.ts
Labels: feature

#12 Feature/dbi-61b - Atualizar o READ ME com o fluxo do git flow (backend)
  README.md
Labels: documentation

#13 Bugfix/DBI-54
  .env.dev
  package.json
  src/env.ts
Labels: bug

#15 Feature/DBI-65 - Substituir console.logs por debug
  .eslintrc.json
  package-lock.json
  package.json
  src/database/config.ts
  src/debugConfig.ts
  src/env.ts
  src/index.ts
  yarn.lock
Labels: enhancement, feature

#14 Feature/dbi-70 - Atualizar grade de tecnologias no documento do projeto
  README.md
Labels: documentation

#16 Feature/dbi 56 - Criar controller para devolver o conteúdo "Guia de Acessibilidade"
  .eslintrc.json
  jest.config.ts
  package-lock.json
  package.json
  src/app/controllers/.gitkeep
  src/app/controllers/GuidesController.ts
  src/app/entities/.gitkeep
  src/app/models/.gitkeep
  src/app/repositories/GuidesRepository.ts
  src/app/routes/routes.ts
  tests/unit/controllers/GuidesController.test.ts
  tsconfig.json
  yarn.lock
Labels: feature

#17 Feature/dbi 58 - Repository para o documento "guides"
  .env
  .eslintrc.json
  package-lock.json
  package.json
  src/app.ts
  src/app/controllers/GuidesController.ts
  src/app/entities/guides.ts
  src/app/models/guides.ts
  src/app/repositories/.gitkeep
  src/app/repositories/GuidesRepository.ts
  src/app/routes/routes.ts
  tests/unit/app/controllers/GuidesController.test.ts
  tests/unit/app/repositories/GuidesRepository.test.ts
  yarn.lock
Labels: feature

#18 bugfix/DBI-58 - Add reference to the controller instance
  src/app.ts
  src/app/routes/routes.ts
Labels: bug

#19 feature/DBI-73 - Adicionar CORS middleware
  package.json
  src/app.ts
Labels: feature

#20 Feature/dbi us003 25 - US003 - [Back] - Criar Repositório
  .env
Labels: feature

#22 Feature/DBI - 24 - Criar Model
  src/app/models/guides.ts
Labels: feature

#24 Create pull_request_template.md
  pull_request_template.md
Labels: documentation

#21 Feature-US003-23
  src/app/entities/guides.ts
Labels: feature

#23 US003 - [Back] - Criar Controller - feat: inserindo post no Controller
  src/app/controllers/GuidesController.ts
  src/app/routes/routes.ts
  tests/unit/app/controllers/GuidesController.test.ts
Labels: feature

#26 feature/DBI-US003-19 - [Back] - Criar rota para página
  package-lock.json
  src/app/routes/routes.ts
  yarn.lock
Labels: feature

#30 fix: Move typescript to dependences, set engines with node version an…
  .eslintrc.json
  package.json
  tsconfig.eslint.json
  tsconfig.json
Labels: release
