Repository dbinclui-org/dbinclui-backend, pull requests merged in 2022-02, with the labels that each got.

#89 Bugfix/DBI-ISSUE-79 - Ajustes nos models
  src/app/entities/categories.ts
  src/app/entities/guides.ts
  src/app/models/categories.ts
Labels: enhancement

#90 Feature/DBI-US013-42 - BACK - Nova rota/controller para consultar guia
  src/app/controllers/DigitalContentsController.ts
  src/app/repositories/DigitalContentsRepository.ts
  src/app/routes/digital-contents-router.ts
  tests/unit/app/controllers/DigitalContentsController.test.ts
Labels: feature

#91 Bugfix/versao mongo db bug
  src/app/repositories/GuidesRepository.ts
Labels: bug

#92 feature/DBI-US013-68 - Nova rota/controller/validaçao para update do conteúdo digital
  src/app/controllers/DigitalContentsController.ts
  src/app/middlewares/validator/DigitalContentValidator.ts
  src/app/repositories/DigitalContentsRepository.ts
  src/app/routes/digital-contents-router.ts
  tests/unit/app/controllers/DigitalContentsController.test.ts
  tests/unit/app/repositories/DigitalContentsRepository.test.ts
  tests/unit/app/validator/DigitalContentValidator.test.ts
Labels: feature

#95 Feature/DBI-US014-48 - Nova rota/controller/validação para exclusão do conteúdo digital de uma categoria
  src/app/controllers/DigitalContentsController.ts
  src/app/entities/digitalContents.ts
  src/app/middlewares/upload/Multer.ts
  src/app/middlewares/validator/DigitalContentValidator.ts
  src/app/models/digitalContents.ts
  src/app/repositories/DigitalContentsRepository.ts
  src/app/routes/digital-contents-router.ts
  tests/unit/app/controllers/DigitalContentsController.test.ts
  tests/unit/app/repositories/DigitalContentsRepository.test.ts
Labels: feature
