Repository dbinclui-org/dbinclui-backend, pull requests merged in 2022-01, with the labels that each got.

#36 Feature/dbi US003 27 - [Back] - Validação
  src/app/middlewares/.gitkeep
  src/app/middlewares/validator/GuidesValidator.ts
  src/app/routes/guides-router.ts
  src/app/routes/routes.ts
  tests/unit/app/validator/GuidesValidator.test.ts
Labels: feature

#37 Feature/dbi 32 Definir Paths no tsconfig.json
  .eslintrc.json
  jest.config.ts
  package-lock.json
  package.json
  tests/unit/app/controllers/GuidesController.test.ts
  tests/unit/app/repositories/GuidesRepository.test.ts
  tsconfig.json
Labels: feature

#43 DBI-US007-39 - Criar entidades no BD
  src/app/entities/categories.ts
  src/app/entities/guides.ts
Labels: feature

#45 DBI-US007--40 - US007 - [Back] - Criar Model
  src/app/models/categories.ts
Labels: feature

#47 Bugfix/DBI-US003-37 - US003 -[Back] - Ajuste na rota
  package-lock.json
  package.json
  src/app/routes/guides-router.ts
Labels: bug

#46 Bugfix/dbi issue 41- ISSUE-41 - [Backend] - Classe GuidesRepository#72
  src/app/repositories/GuidesRepository.ts
  tests/unit/app/repositories/GuidesRepository.test.ts
Labels: bug

#49 Bugfix/DBI-ISSUE-42 - ISSUE-42 - [Config] - Ajustes build.yaml
  .github/workflows/build.yaml
Labels: bug

#51 feature/DBI-US007-37 - [Back] - Criar Repositório
  src/app/repositories/CategoriesRepository.ts
  tests/unit/app/repositories/CategoriesRepository.test.ts
Labels: feature

#48 Feature/DBI-US011-54 - US011 - [Back] - Criar entidades no BD
  src/app/entities/digitalContent.ts
Labels: feature

#52 feature/DBI-US007-35 - US007 - [Back] - Criar Controller
  src/app/controllers/CategoriesController.ts
  src/app/controllers/GuidesController.ts
  tests/unit/app/controllers/CategoriesController.test.ts
Labels: feature

#53 Feature/DBI-US011-52 - [Back] - Criar Model
  package-lock.json
  src/app/models/digitalContent.ts
Labels: feature

#54 Feature/dbi us011 51 - US011 - [Back] - Criar Repositório
  src/app/entities/digitalContents.ts
  src/app/models/digitalContents.ts
  src/app/repositories/DigitalContentsRepository.ts
  tests/unit/app/repositories/DigitalContentsRepository.test.ts
Labels: feature

#56 [config] Fix error when start application in production mode
  babel.config.js
  package.json
  tsconfig.json
Labels: bug

#57 [config] Move libs ts-node and tspath-resolve to production dependences
  package-lock.json
  package.json
Labels: bug

#58 [config] Refactor env.ts
  .gitignore
  src/env.ts
Labels: bug, enhancement

#59 [cofnig] Fix relative path when is production mode
  src/env.ts
Labels: bug, enhancement

#61 [config] Validate if application is running in heroku
  src/env.ts
Labels: enhancement

#60 Feature/dbi us011 61 - US011 - [Back] - Enviar os arquivos para servidor
  .env.sample
  package-lock.json
  package.json
  src/app/middlewares/upload/Multer.ts
  src/app/routes/routes.ts
Labels: feature

#62 Feature/DBI-US011-49 - [Back] - Validação
  src/app/middlewares/validator/DigitalContentValidator.ts
  tests/unit/app/validator/DigitalContentValidator.test.ts
Labels: feature

#64 bugfix/DBI-ISSUE-82 - [Backend] - Adicionar dependência de desenvolvimento
  package-lock.json
  package.json
Labels: enhancement

#65 Feature/DBI-US011-50 - Criar Controller
  jest.config.ts
  src/app.ts
  src/app/controllers/CategoriesController.ts
  src/app/controllers/DigitalContentsController.ts
  src/app/controllers/GuidesController.ts
  src/app/entities/digitalContents.ts
  src/app/models/digitalContents.ts
  src/app/repositories/CategoriesRepository.ts
  src/app/repositories/GuidesRepository.ts
  src/app/routes/categories-router.ts
  src/app/routes/guides-router.ts
  src/app/utils/bindedInstance.ts
  tests/unit/app/controllers/DigitalContentsController.test.ts
  tests/unit/app/repositories/CategoriesRepository.test.ts
  tests/unit/app/repositories/DigitalContentsRepository.test.ts
  tests/unit/app/repositories/GuidesRepository.test.ts
  tsconfig.json
Labels: feature

#67 Feature/DBI-US011-83 - Implementar rota de busca de categoria por guia
  src/app/controllers/CategoriesController.ts
  src/app/repositories/CategoriesRepository.ts
  src/app/routes/categories-router.ts
  tests/unit/app/controllers/CategoriesController.test.ts
  tests/unit/app/repositories/CategoriesRepository.test.ts
Labels: feature

#66 Feature/DBI-US011-53 - US011 - [Back] - Criar rota para página
  package-lock.json
  src/app/middlewares/validator/DigitalContentValidator.ts
  src/app/routes/Digital-contents-router.ts
  src/app/routes/routes.ts
  tests/unit/app/validator/DigitalContentValidator.test.ts
Labels: feature

#70 [config]: Adicionando staging checks
  .github/workflows/build.yaml
  src/app/routes/Digital-contents-router.ts
Labels: enhancement

#72 Feature/DBI-US031-27 - [US031] BACK - Busca encadeada no Banco
  package-lock.json
  src/app/controllers/GuidesController.ts
  src/app/repositories/GuidesRepository.ts
  src/app/routes/Digital-contents-router.ts
  src/app/routes/guides-router.ts
  tests/unit/app/controllers/GuidesController.test.ts
  tests/unit/app/repositories/GuidesRepository.test.ts
Labels: feature

#74 Feature/DBI-US005-18 - BACK - Nova rota/controller para consultar guia
  src/app/controllers/GuidesController.ts
  src/app/repositories/GuidesRepository.ts
  src/app/routes/guides-router.ts
  tests/unit/app/controllers/GuidesController.test.ts
Labels: feature

#73 Feature/DBI-US005-19 - Nova rota/controller/validaçao para update do guia
  src/app/controllers/GuidesController.ts
  src/app/middlewares/validator/GuidesValidator.ts
  src/app/repositories/GuidesRepository.ts
  src/app/routes/guides-router.ts
  tests/unit/app/controllers/GuidesController.test.ts
  tests/unit/app/repositories/GuidesRepository.test.ts
  tests/unit/app/validator/GuidesValidator.test.ts
Labels: feature

#83 bugfix/DBI-ISSUE-82 - [Backend] - Criar teste de erro no consultGuide
  tests/unit/app/controllers/GuidesController.test.ts
Labels: bug

#81 Feature/DBI-US009-33 - BACK - Nova rota/controller para consultar categorias
  src/app/controllers/CategoriesController.ts
  src/app/routes/categories-router.ts
  tests/unit/app/controllers/CategoriesController.test.ts
Labels: feature

#84 bugfix/DBI-ISSUE-76 - Códigos de retorno dos controllers
  src/app/controllers/CategoriesController.ts
  src/app/controllers/DigitalContentsController.ts
  src/app/middlewares/validator/ValidateSchema.ts
  tests/unit/app/controllers/CategoriesController.test.ts
  tests/unit/app/controllers/DigitalContentsController.test.ts
  tests/unit/app/validator/GuidesValidator.test.ts
  tests/unit/app/validator/ValidateSchema.test.ts
Labels: bug

#85 Feature/DBI-US006-21 - Nova rota/controller/validação para exclusão de um guia
  src/app/controllers/GuidesController.ts
  src/app/middlewares/validator/GuidesValidator.ts
  src/app/repositories/DigitalContentsRepository.ts
  src/app/repositories/GuidesRepository.ts
  src/app/routes/guides-router.ts
  tests/unit/app/controllers/GuidesController.test.ts
  tests/unit/app/repositories/DigitalContentsRepository.test.ts
  tests/unit/app/repositories/GuidesRepository.test.ts
  tests/unit/app/validator/GuidesValidator.test.ts
Labels: feature

#88 bugfix/DBI-ISSUE/87- 69 - ISSUE - 87 - [Backend] - Adicionar populate às funções de listagem
  src/app/models/digitalContents.ts
  src/app/repositories/CategoriesRepository.ts
  src/app/repositories/DigitalContentsRepository.ts
  tests/unit/app/repositories/CategoriesRepository.test.ts
  tests/unit/app/repositories/DigitalContentsRepository.test.ts
Labels: enhancement

#86 Bugfix/DBI-ISSUE-75 - Nomenclatura das rotas no padrão REST
  src/app/routes/categories-router.ts
  src/app/routes/digital-contents-router.ts
  src/app/routes/guides-router.ts
  src/app/routes/routes.ts
Labels: bug, feature
